allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  92379c70-ac19-4b2f-8433-9e596b85488f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-15T01:58:34+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0083aea4-e3b7-4627-85ee-400dd3e208a8 # Accordion Items
            handle: null
            instructions: null
            label: Items
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78819c70-ddc9-4644-bb86-e03ca1ca0c54
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9512f336-c6ec-4a90-833e-195e714a138d
        userCondition: null
    thumbFieldKey: null
handle: accordion
hasTitleField: false
icon: plus
name: Accordion
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
