allowLineBreaksInTitles: false
color: green
description: null
fieldLayouts:
  2c836298-a94b-48d9-9375-7b9222781807:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-25T04:54:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7adeac3a-15a2-4d3b-9069-8969df08841b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:58:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7318ab83-35e9-49f3-bee0-be852a027231 # Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8deee8f6-04c6-4b05-94d4-b7066cc53dd7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:54:26+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ae962a30-32f5-4f16-a15d-80f6f7a3f2d9 # Summary
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4324f2a4-3f38-4191-ad0c-fb4e9431fa10
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 53b256c5-8d1b-42d0-9878-88c129a638b9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-25T04:54:26+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 80801f65-acf2-4d04-92c0-df213deaed64 # Content Blocks
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 690bd2c2-abf5-4a28-9305-455fe0093c80
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b3ca5f8c-afcd-4a69-9114-620eab8de93b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-25T04:54:26+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e59c9f67-aad5-41f2-b47e-71bcf09bc841 # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be1900c3-cd23-46c8-a78d-30459bb42326
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 62e2c4e5-1091-4885-8dec-92d38c6f3add
        userCondition: null
    thumbFieldKey: null
handle: contentPage
hasTitleField: true
icon: block-brick
name: 'Content Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
