allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  5b92c245-a5d3-47af-9717-a86ffea099c4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-25T05:31:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7318ab83-35e9-49f3-bee0-be852a027231 # Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f82cf55-12a6-4432-8ae9-06a4b1f83877
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T05:50:49+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: caption
            instructions: null
            label: Caption
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50899c54-a1ae-4ca9-bc40-00ffbd3ddda0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cdf10d7d-c572-45aa-8f98-8445eeeb18eb
        userCondition: null
    thumbFieldKey: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
