allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  018869a5-6675-4318-9cae-8c6905ed9247:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:029d6dd6-768e-4c05-82e4-d6d1fa91fb6d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-25T05:49:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2d17dd68-142c-438c-a33c-be84bf614dbe # Images
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 029d6dd6-768e-4c05-82e4-d6d1fa91fb6d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f56097fb-9eb9-4a5f-b86c-a797192ffe3b
        userCondition: null
    thumbFieldKey: 'layoutElement:029d6dd6-768e-4c05-82e4-d6d1fa91fb6d'
handle: imageGallery
hasTitleField: false
icon: gallery-thumbnails
name: 'Image Gallery'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
