defaultPlacement: end
fieldLayouts:
  dc47be99-6514-480b-8136-e3d352bf9011:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-29T22:29:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: daa58029-5c2e-4353-934d-f12f334eebf2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 006ddf5c-aea8-4b9a-8582-79ef69f9aefe
        userCondition: null
handle: people
name: People
siteSettings:
  24a9a722-d230-49d0-8693-6825092a5675: # $CRAFT_DEFAULT_SITE_NAME
    hasUrls: true
    template: null
    uriFormat: '{{ craft.entries.section("sitemap").type("peopleListing").one().uri|default("people") }}?category={{slug}}'
structure:
  maxLevels: null
  uid: fc82a31d-426f-4580-91a0-81e9634ee501
