columnSuffix: null
handle: accordionItems
instructions: null
name: 'Accordion Items'
searchable: false
settings:
  createButtonLabel: 'Add an accordion'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 8729e2f7-1fc9-4b02-bea2-024f302c227e # Accordion Item
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
