columnSuffix: null
handle: australiaRegion
instructions: null
name: 'Australia Region'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: false
  source: 'group:10f64791-f180-4eb9-ac42-b4d749f3ecce' # Australia Region
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
