columnSuffix: null
handle: bodyText
instructions: null
name: 'Body Text'
searchable: true
settings:
  byteLimit: null
  charLimit: 250
  code: false
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
