columnSuffix: null
handle: contentBlocks
instructions: null
name: 'Content Blocks'
searchable: true
settings:
  createButtonLabel: 'Add a content block'
  defaultIndexViewMode: cards
  enableVersioning: true
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - fb06b793-2038-479d-8cbf-98092b08ba2e # Heading
        -
          - group
          - Text
    -
      __assoc__:
        -
          - uid
          - f797e817-5075-4b7f-871d-4593579a78b6 # Rich Text
        -
          - group
          - Text
    -
      __assoc__:
        -
          - uid
          - 7c1bc3f3-9531-4b93-90bc-3f91a5201fa5 # Accordion
        -
          - group
          - Text
    -
      __assoc__:
        -
          - uid
          - d473b784-8d70-40d9-92a2-941f139ea7e0 # Blockquote
        -
          - group
          - Text
    -
      __assoc__:
        -
          - uid
          - 17602dc9-b8d7-416f-93ab-cd8467d9b76f # Call To Action
        -
          - group
          - Text
    -
      __assoc__:
        -
          - uid
          - fc9c28af-2def-4c85-9022-985bd6c28fb5 # Links & Downloads
        -
          - group
          - Text
    -
      __assoc__:
        -
          - uid
          - 40aec121-6297-4784-afee-cc15f3e675bd # Table
        -
          - group
          - Text
    -
      __assoc__:
        -
          - uid
          - 694fbcbc-c6a1-4224-b3ae-c5e747346b5c # Image
        -
          - group
          - Media
    -
      __assoc__:
        -
          - uid
          - 7988a81d-958b-43e2-906e-98e06ed8f309 # Image Gallery
        -
          - group
          - Media
    -
      __assoc__:
        -
          - uid
          - 3be3c4c6-0838-4340-a6a3-1858bdf8d955 # Form
        -
          - group
          - Widgets
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
