columnSuffix: null
handle: contactLocation
instructions: 'Location label displayed on the contact page (e.g. "Queenstown, New Zealand")'
name: 'Contact Location'
searchable: false
settings:
  byteLimit: null
  charLimit: 120
  code: false
  initialRows: 1
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
