columnSuffix: null
handle: contactInstagramUrl
instructions: 'Instagram profile URL'
name: 'Instagram URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
