columnSuffix: null
handle: contactResponseTime
instructions: 'Response time text (e.g. "Within 24 hours")'
name: 'Contact Response Time'
searchable: false
settings:
  byteLimit: null
  charLimit: 60
  code: false
  initialRows: 1
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
