columnSuffix: null
handle: ctaButtonText
instructions: 'Label for the CTA button'
name: 'CTA Button Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 60
  code: false
  initialRows: 1
  multiline: false
  placeholder: 'Begin an Enquiry'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
