columnSuffix: null
handle: ctaBody
instructions: 'Supporting body paragraph in the CTA section'
name: 'CTA Body'
searchable: false
settings:
  byteLimit: null
  charLimit: 800
  code: false
  initialRows: 5
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
