columnSuffix: null
handle: destinationRegion
instructions: null
name: 'Destination Region'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  source: 'group:99ed816c-569c-4e7d-9a94-306123fd1162' # NZ Region
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
