columnSuffix: null
handle: destinationCountry
instructions: 'Select the country this destination belongs to.'
name: 'Destination Country'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'New Zealand'
        -
          - value
          - new-zealand
    -
      __assoc__:
        -
          - label
          - Australia
        -
          - value
          - australia
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
