columnSuffix: null
handle: gender
instructions: null
name: Gender
searchable: false
settings:
  customOptions: false
  displayAsGraphic: null
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - Female
        -
          - showLabel
          - '1'
        -
          - value
          - female
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Male
        -
          - showLabel
          - '1'
        -
          - value
          - male
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Other
        -
          - showLabel
          - '1'
        -
          - value
          - other
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Buttons
