columnSuffix: null
handle: heroPrimaryButtonUrl
instructions: 'URL for the primary CTA button'
name: 'Hero Primary Button URL'
searchable: false
settings:
  byteLimit: null
  charLimit: 255
  code: false
  initialRows: 1
  multiline: false
  placeholder: /destinations
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
