columnSuffix: null
handle: heroVideoUrl
instructions: 'Background video for the hero section. Upload an MP4 file.'
name: 'Hero Video'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - json
    - video
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:77dcf8f6-0eca-4d1a-a307-ce6088ed61f5' # Videos
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:77dcf8f6-0eca-4d1a-a307-ce6088ed61f5' # Videos
  restrictedLocationSubpath: null
  selectionLabel: 'Select hero video'
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:77dcf8f6-0eca-4d1a-a307-ce6088ed61f5' # Videos
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
