columnSuffix: null
handle: heroSecondaryButtonUrl
instructions: 'URL for the secondary text link'
name: 'Hero Secondary Button URL'
searchable: false
settings:
  byteLimit: null
  charLimit: 255
  code: false
  initialRows: 1
  multiline: false
  placeholder: /signature-journeys
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
