columnSuffix: null
handle: journeyCountry
instructions: 'Country this journey is based in.'
name: 'Journey Country'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'New Zealand'
        -
          - value
          - new-zealand
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Australia
        -
          - value
          - australia
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
