columnSuffix: null
handle: journeyCountry
instructions: 'Country this journey is based in.'
name: 'Journey Country'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - default
          - true
        -
          - label
          - 'New Zealand'
        -
          - value
          - new-zealand
    -
      __assoc__:
        -
          - default
          - false
        -
          - label
          - Australia
        -
          - value
          - australia
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
