columnSuffix: null
handle: journeyCountry
instructions: 'Country this journey is based in.'
name: 'Journey Country'
searchable: false
settings:
  optgroups: false
  options:
    -
      default: true
      label: 'New Zealand'
      value: new-zealand
    -
      default: false
      label: Australia
      value: australia
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
