columnSuffix: null
handle: lpBody
instructions: 'Supporting italic paragraph below the headline'
name: 'LP Body'
searchable: false
settings:
  byteLimit: null
  charLimit: 400
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
