columnSuffix: null
handle: storyLinkText
instructions: 'Label for the story section CTA link (e.g. "Our story")'
name: 'Story Link Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 60
  code: false
  initialRows: 1
  multiline: false
  placeholder: 'Our story'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
