columnSuffix: null
handle: testimonialOrigin
instructions: 'Client location (e.g. "London, United Kingdom")'
name: 'Testimonial Origin'
searchable: false
settings:
  byteLimit: null
  charLimit: 100
  code: false
  initialRows: 1
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
