columnSuffix: null
handle: whyHalcyonPillarIcon
instructions: 'Select an icon for this pillar card'
name: 'Pillar Icon'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Key (Private)'
        -
          - value
          - key
    -
      __assoc__:
        -
          - label
          - 'Compass (Access)'
        -
          - value
          - compass
    -
      __assoc__:
        -
          - label
          - 'Diamond (Quality)'
        -
          - value
          - diamond
    -
      __assoc__:
        -
          - label
          - 'Path (Journey)'
        -
          - value
          - path
    -
      __assoc__:
        -
          - label
          - 'Shield (Trust)'
        -
          - value
          - shield
    -
      __assoc__:
        -
          - label
          - 'Heart (Care)'
        -
          - value
          - heart
    -
      __assoc__:
        -
          - label
          - 'Globe (World)'
        -
          - value
          - globe
    -
      __assoc__:
        -
          - label
          - 'Star (Excellence)'
        -
          - value
          - star
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
