fieldLayouts:
  0342e498-f3c3-42cd-b1b5-31eb63df71ef:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: fullBusinessName
            instructions: null
            label: 'Full Business Name'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee50c376-a9d0-4ce2-8d14-1de9c875950c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: tagline
            instructions: null
            label: Tagline
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7efe5ad-d9ab-411d-b25c-d3258f25bf1a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-28T04:00:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 482f35bf-5e32-4ce7-8982-1a0755932b77 # Text Block
            handle: businessDescription
            instructions: null
            label: 'Business Description'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4492af19-c2a0-4663-8041-ffac3d4034d0
            userCondition: null
            warning: null
            width: 100
        name: 'Key Information'
        uid: 091df2a6-75e1-48e5-91f7-2e8707192fbd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-25T04:30:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 194fbaee-c76c-4faf-b869-08ca938d3fe7 # Email Address
            handle: null
            instructions: null
            label: 'Email Address'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9161ad11-61c5-427e-bcd1-5509e472d1e8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: phoneNumber
            instructions: null
            label: 'Phone Number'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80c11a2e-6e72-4a0e-8292-6cf02c65b6f4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: faxNumber
            instructions: null
            label: 'Fax Number'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8f844be-a649-4c6b-8b1b-392c22935a96
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:30:01+00:00'
            elementCondition: null
            heading: Address
            type: craft\fieldlayoutelements\Heading
            uid: 2a5660cd-3d96-4562-b138-d14612a059a8
            userCondition: null
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: addressLineOne
            instructions: null
            label: 'Address Line One'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3539c53e-adb9-45ff-813e-e05b4e6c8c5e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: addressLineTwo
            instructions: null
            label: 'Address Line Two'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1054a041-1c68-4c32-a0f8-0f1ada6acb4e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: suburb
            instructions: null
            label: Suburb
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a47375e-2504-4cba-93f0-4d94623addfd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: postcode
            instructions: null
            label: Postcode
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f17c609e-3e18-4eed-b63f-b4e4b1e54e1b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:30:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7bbd3fc2-2784-4a32-9281-3db21962504c # State
            handle: null
            instructions: null
            label: State
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8dbe0a91-f7ff-45ac-b90f-a68b5f43d71c
            userCondition: null
            warning: null
            width: 100
        name: Contact
        uid: 26a3d95f-e462-4dd5-9c33-ced677108a8e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: facebookUsername
            instructions: 'The username for your Facebook Page, without the preceding @.'
            label: 'Facebook Username'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a336331d-fa13-48b6-89cd-c90913fee311
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: instagramUsername
            instructions: 'The username for your Instagram Page, without the preceding @.'
            label: 'Instagram Username'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eb4d090-baea-4bbf-b545-f73a3f0d0429
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: linkedinPage
            instructions: 'The slug for your LinkedIn Page, without https://linkedin.com/company/.'
            label: 'LinkedIn Page'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 814a5069-d4fa-4f00-9bf0-e6425e2e9418
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: xHandle
            instructions: 'The handle for your Twitter profile, without the preceding @.'
            label: 'X Handle'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8dbae7fd-2a76-4c66-bbe9-3a1f7bf4c2a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:45:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a133acd-1d63-4b81-b445-8cf2ecd6eb37 # Text
            handle: youtubeChannel
            instructions: 'The channel for your YouTube Page, without https://www.youtube.com/.'
            label: 'YouTube Channel'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86faa38f-9286-4d91-ad59-62960ce1194e
            userCondition: null
            warning: null
            width: 100
        name: Social
        uid: d12b2b7d-752e-485b-875c-fe4bba388a94
        userCondition: null
handle: businessDetails
name: 'Business Details'
sortOrder: 1
