fieldLayouts:
  3e59f02a-4734-4208-81d4-659702d4de77:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-25T04:54:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2aa7b689-24f8-48a6-8355-3d6e61be4c1f # Fallback Image
            handle: fallbackBanner
            instructions: null
            label: Banner
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 959bb11e-cca9-4982-845a-07a00ad1cd71
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-25T04:54:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2aa7b689-24f8-48a6-8355-3d6e61be4c1f # Fallback Image
            handle: fallbackGeneric
            instructions: null
            label: Generic
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40281785-d7c7-4925-ad6b-b57fd81602a4
            userCondition: null
            warning: null
            width: 100
        name: Images
        uid: 2be64520-4ae9-4bee-a1bc-a0d88971bc9a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-23T03:03:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ceca07e6-941b-4381-8e36-e6b760f5f0a6 # Video
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb6a7d8a-ce0a-485a-9dea-552ad553890d
            userCondition: null
            warning: null
            width: 100
        name: Video
        uid: f22d1fe3-f95d-4bde-ad13-d58f5078f5ba
        userCondition: null
    thumbFieldKey: 'layoutElement:cb6a7d8a-ce0a-485a-9dea-552ad553890d'
handle: fallbacks
name: Fallbacks
sortOrder: 4
