defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c1d2e3f4-0001-4000-8000-000000000002 # Destination
handle: destinations
maxAuthors: 1
name: Destinations
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  24a9a722-d230-49d0-8693-6825092a5675: # $CRAFT_DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: sections/destinations/detail.twig
    uriFormat: '{% set r = object.nzRegion.one() ?? object.australiaRegion.one() %}destinations/{{ r.slug }}/{{ object.slug }}'
structure:
  maxLevels: null
  uid: 7fb1eac8-73f5-4735-bb35-2976b0231f38
type: structure
