defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c1d2e3f4-0002-4000-8000-000000000002 # Signature Journey
handle: signatureJourneys
maxAuthors: 1
name: 'Signature Journeys'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  24a9a722-d230-49d0-8693-6825092a5675: # $CRAFT_DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: sections/signature-journeys/detail
    uriFormat: 'signature-journeys/{slug}'
type: channel
